kind: Secret
apiVersion: v1
metadata:
  name: binder-secret
type: Opaque
data:
  {{ if .Values.registry.enabled -}}
  config.json: |
    {{ b64enc (printf "{\"auths\": { \"https://%s\": { \"email\": \"not@val.id\", \"auth\": \"%s\" } } }" .Values.registry.host (b64enc (printf "%s:%s" .Values.registry.username .Values.registry.password) ) ) }}
  {{- end }}
  binder.hub-token: {{ .Values.jupyterhub.hub.services.binder.apiToken | b64enc | quote }}
