{{- $HTTPS := .Values.proxy.https.enabled -}}
{{- $offloadHTTPS := and $HTTPS (eq .Values.proxy.https.type "offload") -}}
{{- $manualHTTPS := and $HTTPS (eq .Values.proxy.https.type "manual") -}}
{{- $manualHTTPSwithsecret := and $HTTPS (eq .Values.proxy.https.type "secret") -}}
{{- $serveHTTPS := and $HTTPS (or $manualHTTPS $manualHTTPSwithsecret) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-traefik-config
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
data:
  traefik.toml: |
    # traefik.toml
    {{- if .Values.proxy.traefik.debug.enabled }}
    debug = true
    {{- else }}
    logLevel = "INFO"
    {{- end }}
    {{- if .Values.proxy.traefik.sendAnonymousUsage }}
    sendAnonymousUsage = true
    {{- end }}
    {{- if $serveHTTPS }}
    defaultEntryPoints = ["http", "https"]
    {{- else }}
    defaultEntryPoints = ["http"]
    {{- end }}
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = {{ .Values.proxy.traefik.gzip.enabled }}
        {{- if $serveHTTPS }}
        [entryPoints.http.redirect]
          regex = "^http://(.*)"
          replacement = "https://$1"
          {{- if .Values.proxy.https.permanentRedirect }}
          permanent = true
          {{- end }}
        {{- end }}
      {{- if $serveHTTPS }}
      [entryPoints.https]
      address = ":443"
      compress = {{ .Values.proxy.traefik.gzip.enabled }}
        {{- if (or $manualHTTPS $manualHTTPSwithsecret) }}
        [entryPoints.https.tls]
          [[entryPoints.https.tls.certificates]]
          CertFile = "/ssl/tls.crt"
          KeyFile = "/ssl/tls.key"
        {{- end }}
      {{- end}}

      [entryPoints.api]
      address = ":8001"
        [entryPoints.api.auth]
          [entryPoints.api.auth.basic]
            usersFile = "/htpasswd/htpasswd"

    {{- if .Values.proxy.traefik.traefikLogFormat }}
    [traefikLog]
      format = {{ .Values.proxy.traefik.traefikLogFormat | quote }}
    {{- end }}

    # log errors, which could be proxy errors
    [accessLog]
    format = "json"
    [accessLog.filters]
    statusCodes = ["0-999"]

    [accessLog.fields.headers]
    [accessLog.fields.headers.names]
    Authorization = "redact"
    Cookie = "redact"
    Set-Cookie = "redact"
    X-Xsrftoken = "redact"

    [respondingTimeouts]
    idleTimeout = "10m0s"

    [consul]
    watch = true
    prefix = {{ .Values.proxy.consul.traefikPrefix | quote }}

    [api]
      entryPoint = "api"
      dashboard = false
    {{- if .Values.proxy.traefik.metrics.prometheus.enabled }}
    [metrics]
      [metrics.prometheus]
        entryPoint = "api"
    {{- end }}
