{{- $HTTPS := .Values.proxy.https.enabled -}}
{{- $autoHTTPS := and $HTTPS (and (eq .Values.proxy.https.type "letsencrypt") .Values.proxy.https.hosts) -}}
{{- $manualHTTPS := and $HTTPS (eq .Values.proxy.https.type "manual") -}}
{{- $manualHTTPSwithsecret := and $HTTPS (eq .Values.proxy.https.type "secret") -}}
{{- if .Values.proxy.networkPolicy.enabled -}}
#
{{- /*

Network policy for jupyterhub traefik proxy:

- only hub and proxy can talk to etcd
- only hub can talk to proxy api
- proxy only needs to talk to the hub

*/}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: proxy-traefik
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- $_ := merge (dict "componentLabel" "proxy") . }}
      {{- include "jupyterhub.matchLabels" $_ | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
      - protocol: TCP
        port: 80
      - protocol: TCP
        port: 443
    - from:
        - podSelector:
            matchLabels:
              hub.jupyter.org/network-access-proxy-http: "true"
      ports:
        - protocol: TCP
          port: 8000
    - from:
        - podSelector:
            matchLabels:
              hub.jupyter.org/network-access-proxy-api: "true"
      ports:
        - protocol: TCP
          port: 8080
  egress:
    {{- /*
    The default is to allow all egress for proxy If you want to restrict it the
    following egress is required
      -  hub:8081
      -  singleuser:8888
      -  Kubernetes api-server
    */}}
    {{- if .Values.proxy.networkPolicy.egress }}
    {{- .Values.proxy.networkPolicy.egress | toYaml | trimSuffix "\n" | nindent 4 }}
    {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: proxy-etcd
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- $_ := merge (dict "componentLabel" "proxy-etcd") . }}
      {{- include "jupyterhub.matchLabels" $_ | nindent 6 }}

  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              hub.jupyter.org/network-access-proxy-etcd: "true"
      ports:
        - protocol: TCP
          port: 2379
    - from:
        - podSelector:
            matchLabels:
              {{- $_ := merge (dict "componentLabel" "proxy-etcd") . }}
              {{- include "jupyterhub.matchLabels" $_ | nindent 14 }}
      ports:
        - protocol: TCP
          port: 2380
{{- end }}
