{{- $HTTPS := .Values.proxy.https.enabled -}}
{{- $autoHTTPS := and $HTTPS (and (eq .Values.proxy.https.type "letsencrypt") .Values.proxy.https.hosts) -}}
{{- $manualHTTPS := and $HTTPS (eq .Values.proxy.https.type "manual") -}}
{{- $manualHTTPSwithsecret := and $HTTPS (eq .Values.proxy.https.type "secret") -}}
{{- if .Values.proxy.networkPolicy.enabled -}}
#
{{- /*

Network policy for jupyterhub traefik proxy:

- only hub and proxy can talk to etcd
- only hub can talk to proxy api
- proxy only needs to talk to the hub

*/}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: proxy
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- $_ := merge (dict "componentLabel" "proxy") . }}
      {{- include "jupyterhub.matchLabels" $_ | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
      - protocol: TCP
        port: 80
      - protocol: TCP
        port: 443
    - from:
        - podSelector:
            matchLabels:
              hub.jupyter.org/network-access-proxy-api: "true"
      ports:
        - protocol: TCP
          port: 8001
    {{- /* Useful if you want to give proxy access to pods from other namespaces */}}
    {{- if .Values.proxy.networkPolicy.ingress}}
    {{- .Values.proxy.networkPolicy.ingress | toYaml | trimSuffix "\n" | nindent 4 }}
    {{- end }}
  egress:
    {{- /*
    The default is to allow all egress for proxy If you want to restrict it the
    following egress is required
      - hub:8081
      - singleuser:8888
      - Kubernetes api-server
      - Kubernetes DNS
    */}}
    {{- if .Values.proxy.networkPolicy.egress }}
    {{- .Values.proxy.networkPolicy.egress | toYaml | trimSuffix "\n" | nindent 4 }}
    {{- end }}
{{- end }}
