{{ if .Values.scheduler.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-scheduler-config
data:
  policy.json: |
    {
      "kind": "Policy",
      "apiVersion": "v1",
      "predicates": [
        {
          "name": "PodFitsPorts"
        },
        {
          "name": "PodFitsHostPorts"
        },
        {
          "name": "PodFitsResources"
        },
        {
          "name": "HostName"
        },
        {
          "name": "MatchNodeSelector"
        },
        {
          "name": "NoVolumeZoneConflict"
        },
        {
          "name": "MaxEBSVolumeCount"
        },
        {
          "name": "MaxGCEPDVolumeCount"
        },
        {
          "name": "MaxAzureDiskVolumeCount"
        },
        {
          "name": "MatchInterPodAffinity"
        },
        {
          "name": "NoDiskConflict"
        },
        {
          "name": "GeneralPredicates"
        },
        {
          "name": "CheckNodeMemoryPressure"
        },
        {
          "name": "CheckNodeDiskPressure"
        },
        {
          "name": "PodToleratesNodeTaints"
        },
        {
          "name": "CheckVolumeBinding"
        }
      ],
      "priorities": [
        {
          "name": "ServiceSpreadingPriority",
          "weight": 1
        },
        {
          "name": "EqualPriority",
          "weight": 1
        },
        {
          "name": "ImageLocalityPriority",
          "weight": 1
        },
        {
          "name": "MostRequestedPriority",
          "weight": 1
        },
        {
          "name": "SelectorSpreadPriority",
          "weight": 1
        },
        {
          "name": "InterPodAffinityPriority",
          "weight": 1
        },
        {
          "name": "LeastRequestedPriority",
          "weight": 1
        },
        {
          "name": "BalancedResourceAllocation",
          "weight": 1
        },
        {
          "name": "NodePreferAvoidPodsPriority",
          "weight": 10000
        },
        {
          "name": "NodeAffinityPriority",
          "weight": 1
        },
        {
          "name": "TaintTolerationPriority",
          "weight": 1
        },
        {
          "name": "GPUAllocationPriority",
          "weight": 10
        }
      ],
      "hardPodAffinitySymmetricWeight" : 10,
      "alwaysCheckAllPredicates" : true
    }

{{ end }}
