
{{- /*
These user-placeholder pods can be used to test cluster autoscaling in a
controlled fashion.

Example:
$ echo 'Simulating four users...'
$ kubectl scale sts/user-placeholder --replicas 4
*/}}
{{- if .Values.scheduling.userPlaceholder.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-placeholder
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  podManagementPolicy: Parallel
  replicas: {{ .Values.scheduling.userPlaceholder.replicas }}
  selector:
    matchLabels:
      {{- include "jupyterhub.matchLabels" . | nindent 6 }}
  serviceName: "user-placeholder"
  template:
    metadata:
      labels:
        {{- /* Changes here will cause the Deployment to restart the pods. */}}
        {{- include "jupyterhub.matchLabels" . | nindent 8 }}
    spec:
      {{- if .Values.scheduling.podPriority.enabled }}
      priorityClassName: {{ .Release.Name }}-user-placeholder-priority
      {{- end }}
      {{- if .Values.scheduling.userScheduler.enabled }}
      schedulerName: {{ .Release.Name }}-user-scheduler
      {{- end }}
      tolerations:
        {{- include "jupyterhub.userTolerations" . | nindent 8 }}
      nodeSelector: {{ toJson .Values.singleuser.nodeSelector }}
      affinity:
        # We ideally want *all* our placeholder pods to be in the newest
        # autoscaled node. This way, user pods are packed in as tightly
        # as possible, instead of nodes 'wasting' some resources on
        # user placeholder pods that won't get pre-empted. Part of
        # accomplishing this is:
        #   1. Make sure the placeholder pods all hang out together.
        #      This is accomplished using the custom user scheduler
        #      right now.
        #   2. Try and make sure user pods & placeholder pods do not
        #      mix. This anti affinity term helps with that, although
        #      there also needs to be active descheduling.
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: component
                      operator: In
                      values:
                        - singleuser-server
                topologyKey: kubernetes.io/hostname
              weight: 100
      {{- if include "jupyterhub.userAffinity" . }}
        {{- include "jupyterhub.userAffinity" . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 0
      automountServiceAccountToken: false
      containers:
        - name: pause
          image: {{ .Values.prePuller.pause.image.name }}:{{ .Values.prePuller.pause.image.tag }}
          resources:
            {{- include "jupyterhub.resources" . | nindent 12 }}
{{- end }}
