apiVersion: v1
kind: Service
metadata:
  name: proxy-etcd
  labels:
    {{- $_ := merge (dict "componentLabel" "proxy-etcd") . }}
    {{- include "jupyterhub.labels" $_ | nindent 4 }}
spec:
  ports:
  - port: 2380
    name: etcd-server
  - port: 2379
    name: etcd-client
  selector:
    {{- include "jupyterhub.matchLabels" $_ | nindent 6 }}
