name: jupyterhub
version: v0.7-c14a5462
appVersion: v0.9.2
description: Multi-user Jupyter installation
home: https://z2jh.jupyter.org
sources:
  - https://github.com/jupyterhub/zero-to-jupyterhub-k8s
icon: https://jupyter.org/assets/hublogo.svg
kubeVersion: '>=1.9.0-0'
tillerVersion: '>=2.9.1-0'
