hub:
  service:
    ports:
      nodePort:
  baseUrl: /
  cookieSecret: ''
  publicURL:
  nodeSelector: {}
  concurrentSpawnLimit: 64
  activeServerLimit:
  db:
    type: sqlite-pvc
    upgrade:
    pvc:
      annotations: {}
      selector: {}
      subPath:
      storageClassName:
    url:
  labels:
    test-label: test-value
  annotations:
    test-annotation: test-value
  extraConfig: {}
  extraConfigMap: {}
  extraEnv: {}
  extraContainers: []
  extraVolumes: []
  extraVolumeMounts: []
  services: {}
  imagePullPolicy: IfNotPresent
  pdb:
    enabled: true
  networkPolicy:
    enabled: true
    egress:
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0


rbac:
  enabled: true


proxy:
  secretToken: '0000000000000000000000000000000000000000000000000000000000000000'
  service:
    type: LoadBalancer
    labels: {}
    annotations: {}
    nodePorts:
      http:
      https:
  nginx:
    image:
      name: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
      tag: 0.9.0
      pullPolicy: IfNotPresent
    proxyBodySize: 64m
    resources: {}
  lego:
    image:
      name: jetstack/kube-lego
      # We need a couple of fixes related to ingress.provider that are in master
      # When 0.1.6 is released, switch to that!
      tag: master-2368
    resources: {}
  labels: {}
  annotations: {}
  nodeSelector: {}
  pdb:
    enabled: true
  https:
    enabled: true
    type: letsencrypt
    letsencrypt:
      contactEmail: ''
    manual:
      key:
      cert:
    hosts: []
  networkPolicy:
    enabled: true
    egress:
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0


auth:
  type: dummy
  whitelist:
    users:
  admin:
    access: true
    users:
  dummy:
    password:
  state:
    enabled: true
    cryptoKey: '0000000000000000000000000000000000000000000000000000000000000000'


singleuser:
  networkTools:
    image:
      name: jupyterhub/k8s-network-tools
      tag: generated-by-chartpress
  cloudMetadata:
    enabled: true
    ip: 169.254.169.254
  networkPolicy:
    enabled: true
    egress:
    # Required egress is handled by other rules so it's safe to modify this
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0
              except:
                - 169.254.169.254/32
  extraLabels: {}
  extraEnv: {}
  lifecycleHooks:
  initContainers:
  nodeSelector: {}
  uid: 1000
  fsGid: 100
  serviceAccountName:
  schedulerStrategy:
  storage:
    type: dynamic
    extraVolumes: []
    extraVolumeMounts: []
    static:
      pvcName:
      subPath: '{username}'
    capacity: 10Gi
    homeMountPath: /home/jovyan
    dynamic:
      storageClass:
      pvcNameTemplate: claim-{username}{servername}
      volumeNameTemplate: volume-{username}{servername}
      storageAccessModes:
        - ReadWriteOnce
  image:
    name: jupyterhub/k8s-singleuser-sample
    tag: generated-by-chartpress
    pullPolicy: IfNotPresent
  startTimeout: 300
  cpu:
    limit:
    guarantee:
  memory:
    limit:
    guarantee: 1G
  cmd: jupyterhub-singleuser
  defaultUrl:


prePuller:
  hook:
    enabled: true
    extraEnv: {}
    image:
      name: jupyterhub/k8s-image-awaiter
      tag: generated-by-chartpress
  continuous:
    enabled: true
  pause:
    image:
      name: gcr.io/google_containers/pause
      tag: '3.0'


ingress:
  enabled: true
  annotations: {}
  hosts: []
  tls:


cull:
  enabled: true
  users: false


debug:
  enabled: true
